### ISSUE TITLE
Test strokes offset by cursor position

### ISSUE THREAD

**Issue by eblock** [eblock/fossil#3]
Attempt offsetting strokes for large type and background rectangle using cursor position. Would be cool if the strokes could use CSS multiple effect too.

**Comment by tyler-yin** [comment]
Multiply effect is working. Currently testing stroke-offsetting with CSS `text-shadow` and `-webkit-text-stroke` properties.

Reference:
https://www.w3schools.com/cssref/css3_pr_text-shadow.asp
https://css-tricks.com/adding-stroke-to-web-text/

**Comment by eblock** [comment]
Omg multiply effect!!!
